/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "prueba.h"

float *
suma_1_svc(operandos *argp, struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */

	result = (argp->a) + (argp->b);
	return &result;
}

float *
multiplicacion_1_svc(operandos *argp, struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */

	result = (argp->a) * (argp->b);
	return &result;
}

float *
division_1_svc(operandos *argp, struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */

	result = (argp->a) / (argp->b);
	return &result;
}
