/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "prueba.h"

#include <math.h> //Para fabs
#include <time.h> //Para medir lo que tarda la ejecución

#define COTA_ERROR 1.0e-6

void calculadora_prog_1(char *host, char *operation, operandos *arg_operandos)
{

	CLIENT *clnt;
	float  *result;
	time_t start, end; //Variables auxiliares para medir el tiempo

	#ifndef	DEBUG
		clnt = clnt_create (host, CALCULADORA_PROG, CALCULADORA_VERS, "udp");
		if (clnt == NULL) {
			clnt_pcreateerror (host);
			exit (1);
		}
	#endif	/* DEBUG */


	switch (*operation) {
		case '1':
			time(&start);	//Apunta en momento de inicio

			for (int i = 0; i < 100000; i++) {	//100.000 llamadas a sumar

					result = suma_1(arg_operandos, clnt);
				if (result == (float *) NULL) {
					clnt_perror (clnt, "call failed");
				}
				printf("%d.- El resultado es %.2f\n", i, *result);

			}

			time(&end);	//Apunta el momento de finalización
			time_t time_taken = end - start;	//Se calcula el tiempo invertido

			printf("Tiempo invertido = %li seg\n", time_taken);

		break;

		case '2':
			result = multiplicacion_1(arg_operandos, clnt);
			if (result == (float *) NULL) {
				clnt_perror (clnt, "call failed");
			}
			printf("El resultado es %.2f\n", *result);
		break;

		case '3':
			result = division_1(arg_operandos, clnt);
			if (result == (float *) NULL) {
				clnt_perror (clnt, "call failed");
			}
			printf("El resultado es %.2f\n", *result);
		break;
	}

	#ifndef	DEBUG
		clnt_destroy (clnt);
	#endif	 /* DEBUG */
}


int main (int argc, char *argv[])
{
	char *host;
	char operation[1];

	char *argoperation = argv[2];

	operandos arg_operandos;

	if (argc < 5) {
		printf ("Uso: %s dirección_servidor operación operando1 operando2\n", argv[0]);
		exit (1);
	}

	host = argv[1];

	if (strcmp(argoperation, "suma") == 0 || strcmp(argoperation, "+") == 0) {
		*operation='1';
	}
	else if (strcmp(argoperation, "multiplicacion") == 0 || strcmp(argoperation, "x") == 0) {
		*operation='2';
	}
	else if (strcmp(argoperation, "division") == 0 || strcmp(argoperation, "/") == 0) {
		if(fabs( atof(argv[4]) ) < COTA_ERROR){
			printf("ERROR. No se puede dividir entre 0.\n");
			exit(-1);
		}
		*operation='3';
	}
	else{
		printf ("%s is not a valid operation\n", argv[2]);
		exit (2);
	}

	arg_operandos.a = atof(argv[3]);
	arg_operandos.b = atof(argv[4]);

	calculadora_prog_1 (host, operation, &arg_operandos);
	//exit (0);
}
